---
# This playbook configures a standard 24 port template switch, ie 
# Port 1 always connects to the upstream Router 
# Port 2 always connects to the AP
# Port 3 always connects to the Printer, and so on

    - name: Configure switch Port1
      cisco.meraki.devices_switch_ports:
        meraki_api_key: "{{ meraki_api_key }}"
        meraki_suppress_logging: true
        state: present
        serial: "{{ switch_serial }}"
        name: "Uplink to Gateway RW"
        type: trunk
        vlan: 1
        portId: 1

    - name: Configure switch Port2
      cisco.meraki.devices_switch_ports:
        meraki_api_key: "{{ meraki_api_key }}"
        meraki_suppress_logging: true
        state: present
        serial: "{{ switch_serial }}"
        name: "Link to Access Point"
        type: trunk
        vlan: 1
        allowedVlans: 1,20,10
        portId: 2

    - name: Configure switch Port3
      cisco.meraki.devices_switch_ports:
        meraki_api_key: "{{ meraki_api_key }}"
        meraki_suppress_logging: true
        state: present
        serial: "{{ switch_serial }}"
        name: POS Printer
        type: access
        vlan: 20
        portId: 3

    - name: Configure switch Port4
      cisco.meraki.devices_switch_ports:
        meraki_api_key: "{{ meraki_api_key }}"
        meraki_suppress_logging: true
        state: present
        serial: "{{ switch_serial }}"
        name: Office Printer
        type: access
        vlan: 20
        portId: 4

    - name: Configure switch Port5
      cisco.meraki.devices_switch_ports:
        meraki_api_key: "{{ meraki_api_key }}"
        meraki_suppress_logging: true
        state: present
        serial: "{{ switch_serial }}"
        name: PoS Terminal
        type: access
        vlan: 10
        portId: 5

    - name: Configure switch Port6
      cisco.meraki.devices_switch_ports:
        meraki_api_key: "{{ meraki_api_key }}"
        meraki_suppress_logging: true
        state: present
        serial: "{{ switch_serial }}"
        name: Office User+Phone Access
        type: access
        vlan: 10
        voiceVlan: 11
        portId: 6

    - name: Configure switch Port7
      cisco.meraki.devices_switch_ports:
        meraki_api_key: "{{ meraki_api_key }}"
        meraki_suppress_logging: true
        state: present
        serial: "{{ switch_serial }}"
        name: Sales User+Phone Access
        type: access
        vlan: 10
        voiceVlan: 11
        portId: 7

    - name: Configure switch Port8
      cisco.meraki.devices_switch_ports:
        meraki_api_key: "{{ meraki_api_key }}"
        meraki_suppress_logging: true
        state: present
        serial: "{{ switch_serial }}"
        name: Sales PC Access Only
        type: access
        vlan: 10
        portId: 8
